### ISSUE TITLE
No module named 'manifest'

### ISSUE THREAD

**Issue by duongnhatthang** [HazyResearch/fm_data_tasks#8]
Hi,
I ran your code using conda with python 3.9 on MacOS and a Ubuntu kernel on Window WSL2.
I met with the error:

`poetry run python -m fm_data_tasks.run_inference --help
Traceback (most recent call last):
  File "/home/thangduong/miniconda3/envs/fm_data_tasks/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/thangduong/miniconda3/envs/fm_data_tasks/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/thangduong/fm_data_tasks/fm_data_tasks/run_inference.py", line 8, in <module>
    from manifest import Manifest
ModuleNotFoundError: No module named 'manifest'`

Also, you got a typo in the instruction:
`poetry run python3 -m fm_data_tasks.run_infernece --help`
run_infernece  -> run_inference 

You should also add a recommended python version, imho.

**Comment by duongnhatthang** [comment]
Just found the solution: I need to install your package in a different repo (https://github.com/HazyResearch/manifest)
You should add `pip install manifest-ml` to your readme file
